= Introduction
Fundamental course for cloud computing

== Objectives
- Define generative artificial intelligence
- Define foundation models
- Discuss different cases
- Identify features and benefits of AWS

== What is Generative IA ? 
- Creation of content and ideas including:
 * stories
 * conversations
 * images
 * music

== How it differs from traditiona IA
It is a subset of machine learning 

|===
|Machine Learning                   |Generative IA 

|task based on data own data        |Pre-trained data on massive ammount 
|Sentient analysys Image class.     |Multiple tasks on same process
|Only one task with much process    |Works on patterns and relationships

== Foundation models (FMs)
At is core, it hav emultiple machine learning models that includes: 
 * Text generation
 * data summarization
 * Information extraction
 * Question and answer control
 * Chatbot interaction

== Comparisson of Traditional and foundational models
 While traditional models work for an specific tasks, the foundational models
 can adapt to several tasks, while also be customizable to perform domain-specific
 function. While also using less resources

== Prompt Engineering
It alls starts with a Prompt, to obtain an inference (response to Prompt)

== Prompt engineering IT 
- Example: Using Amazon Q Developer:
    - Prompt        : write a function to verify an email address.
    - Inference     : Functions one might use for the solution

== Fundation Model Types

* Text-to-Text      : are build for naturale language
* Text-to-embeddings: compares text input with indexed data, like search engines
* MutiModal         : genearet different formats such as images and text

== Use cases for audio::

=== Enhance Customer Experiences
    * Chatbots and virtual assistances  : Streamline customer self-services reducing operational costs
    * Agent assist and call analytics   : Summarize customer conversation and analyze interactions
    * Personalization                   : Deliver better experience depending the client

=== Boost employee productivity
    * Conversationar search             : Improve search of information
    * Code generation                   : Code suggestions
    * Automated Report Generation       : Financial, summaries and projection reports

=== Optimize processes
    * Intelligent document processing   : extract and Summarize information from doc
    * Data augmentation                 :  Generate syntetic data to train ML model where dataset is small,imbalanced or sensitive
    * Supply chain optimization         : Improve logistics and reduce costs evaluating and optimizing different scenarios

== Enhance Creativity and content Creation  
    * AI-Marketing content              : Social media update, email newsletters
    * AI-Sales content                  : personalize emails base on customer data
    * New Product Development           : Generate multiple design prototypes on certain inputs and constrains

== Per industry

=== Health care:
    * Create transcripts, extact key details and summaries for clinical patien interaction
    * Interpret medical images
    * Personalize medicine based on genetics, lifestyle and synthoms


